Build: abi-check: don't mix tabs and spaces

diff --git a/abi-check b/abi-check
--- a/abi-check
+++ b/abi-check
@@ -9,9 +9,9 @@ PACKAGE=$1; shift
 
 function tag() {
     if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]; then
-	echo Pacemaker-$1
+        echo Pacemaker-$1
     else
-	echo $1
+        echo $1
     fi
 }
 
@@ -26,10 +26,10 @@ function extract() {
     VERSION=$2
 
     if [ $VERSION = HEAD ]; then
-	rm -rf abi_dumps/$PACKAGE/${PACKAGE}_$VERSION.abi.tar.gz
+        rm -rf abi_dumps/$PACKAGE/${PACKAGE}_$VERSION.abi.tar.gz
 
     elif [ -f abi_dumps/$PACKAGE/${PACKAGE}_$VERSION.abi.tar.gz ]; then
-	return
+        return
     fi
 
     echo "Building ABI dump for $*"
@@ -51,7 +51,7 @@ function extract() {
     $VERSION
 </version>
 <headers>
-	$BUILD_ROOT/root/usr/include/pacemaker/crm
+        $BUILD_ROOT/root/usr/include/pacemaker/crm
 </headers>
 <libs>
 EOF
@@ -60,14 +60,14 @@ EOF
     ( cd $BUILD_ROOT && ./configure  --disable-fatal-warnings )
     make -C $BUILD_ROOT V=0 DESTDIR=${BUILD_ROOT}/root install
     if [ $? != 0 ]; then
-	echo "Build for $TAG failed. Repair, populate <libs/> and re-run: "
-	echo "  abi-compliance-checker -l $PACKAGE -dump_abi $DESC"
-	echo ""
-	echo "To find libraries after building:"
-	echo "  find $BUILD_ROOT/root -name "*.so" -print"
+        echo "Build for $TAG failed. Repair, populate <libs/> and re-run: "
+        echo "  abi-compliance-checker -l $PACKAGE -dump_abi $DESC"
+        echo ""
+        echo "To find libraries after building:"
+        echo "  find $BUILD_ROOT/root -name "*.so" -print"
 
     else
-	find $BUILD_ROOT/root -name "*.so" -print >> $DESC
+        find $BUILD_ROOT/root -name "*.so" -print >> $DESC
     fi
 
     cat<<EOF>>$DESC
@@ -76,10 +76,10 @@ EOF
 EOF
 
     if [ $DUMP = 1 ]; then
-	abi-compliance-checker -l $PACKAGE -dump_abi $DESC
-	rm -rf $BUILD_ROOT
+        abi-compliance-checker -l $PACKAGE -dump_abi $DESC
+        rm -rf $BUILD_ROOT
     else
-	exit 1
+        exit 1
     fi
 }
 
@@ -94,10 +94,10 @@ if [ $# = 2 ]; then
     V2=`version $2`
 
     abi-compliance-checker -l ${PACKAGE} \
-	-d1 abi_dumps/${PACKAGE}/${PACKAGE}_${V1}.abi.tar.gz \
-	-d2 abi_dumps/${PACKAGE}/${PACKAGE}_${V2}.abi.tar.gz
+        -d1 abi_dumps/${PACKAGE}/${PACKAGE}_${V1}.abi.tar.gz \
+        -d2 abi_dumps/${PACKAGE}/${PACKAGE}_${V2}.abi.tar.gz
 
     if [ $UPLOAD = 1 -a -d compat_reports/pacemaker/${V1}_to_${V2} ]; then
-	rsync -azxlSD --progress compat_reports/pacemaker/${V1}_to_${V2} root@www.clusterlabs.org:/var/www/html/abi/pacemaker/
+        rsync -azxlSD --progress compat_reports/pacemaker/${V1}_to_${V2} root@www.clusterlabs.org:/var/www/html/abi/pacemaker/
     fi
 fi
