Refactor: CTS: don't mix tabs and spaces in cts-pengine

diff --git a/cts/cts-pengine.in b/cts/cts-pengine.in
--- a/cts/cts-pengine.in
+++ b/cts/cts-pengine.in
@@ -53,26 +53,26 @@ single_test=
 
 while true ; do
     case "$1" in
-	-V|--verbose) verbose=1; shift;;
-	-v|--valgrind)
-	    export G_SLICE=always-malloc
-	    VALGRIND_CMD="valgrind -q --gen-suppressions=all --log-file=%q{valgrind_output} --show-reachable=no --leak-check=full --trace-children=no --time-stamp=yes --num-callers=20 --suppressions=@datadir@/@PACKAGE@/tests/valgrind-pcmk.suppressions"
-	    test_binary=
-	    shift;;
-	--valgrind-dhat)
-	    VALGRIND_CMD="valgrind --log-file=%q{valgrind_output} --show-top-n=100 --num-callers=4 --time-stamp=yes --trace-children=no --tool=exp-dhat"
-	    test_binary=
-	    shift;;
-	--valgrind-skip-output)
-	    VALGRIND_SKIP_OUTPUT=1
-	    shift;;
-	--run) single_test="$2"; shift; shift; break;;
-	-b|--binary) test_binary=$2; PCMK_schema_directory=""; shift; shift;;
-	-i|--io-dir) io_dir=$2; shift; shift;;
-	-?|--help) echo "$0 [--binary name] [--force-local]"; shift; exit 0;;
-	--) shift ; break ;;
-	"") break;;
-	*) echo "unknown option: $1"; exit 1;;
+        -V|--verbose) verbose=1; shift;;
+        -v|--valgrind)
+            export G_SLICE=always-malloc
+            VALGRIND_CMD="valgrind -q --gen-suppressions=all --log-file=%q{valgrind_output} --show-reachable=no --leak-check=full --trace-children=no --time-stamp=yes --num-callers=20 --suppressions=@datadir@/@PACKAGE@/tests/valgrind-pcmk.suppressions"
+            test_binary=
+            shift;;
+        --valgrind-dhat)
+            VALGRIND_CMD="valgrind --log-file=%q{valgrind_output} --show-top-n=100 --num-callers=4 --time-stamp=yes --trace-children=no --tool=exp-dhat"
+            test_binary=
+            shift;;
+        --valgrind-skip-output)
+            VALGRIND_SKIP_OUTPUT=1
+            shift;;
+        --run) single_test="$2"; shift; shift; break;;
+        -b|--binary) test_binary=$2; PCMK_schema_directory=""; shift; shift;;
+        -i|--io-dir) io_dir=$2; shift; shift;;
+        -?|--help) echo "$0 [--binary name] [--force-local]"; shift; exit 0;;
+        --) shift ; break ;;
+        "") break;;
+        *) echo "unknown option: $1"; exit 1;;
     esac
 done
 
@@ -136,155 +136,151 @@ function do_test {
     export valgrind_output
 
     if [ "x$1" = "x--rc" ]; then
-	expected_rc=$2
-	shift; shift;
+        expected_rc=$2
+        shift; shift;
     fi
 
     show_test "$base" "$name"
 
     if [ ! -f $input ]; then
-	error "No input";
-	did_fail=1
-	num_failed=`expr $num_failed + $did_fail`
-	return;
+        error "No input";
+        did_fail=1
+        num_failed=`expr $num_failed + $did_fail`
+        return;
     fi
 
     if [ "$create_mode" != "true" -a ! -f $expected ]; then
-	error "no stored output";
-#	return;
+        error "no stored output";
     fi
 
 #    ../admin/crm_verify -X $input
     if [ ! -z $single_test ]; then
-	echo CIB_shadow_dir=$io_dir $test_cmd -x $input -D $dot_output -G $output -S $*
-	CIB_shadow_dir=$io_dir $test_cmd -x $input -D $dot_output -G $output -S $* 2>&1 | tee $summary_output
+        echo CIB_shadow_dir=$io_dir $test_cmd -x $input -D $dot_output -G $output -S $*
+        CIB_shadow_dir=$io_dir $test_cmd -x $input -D $dot_output -G $output -S $* 2>&1 | tee $summary_output
     else
-	CIB_shadow_dir=$io_dir $test_cmd -x $input -S &> $summary_output
+        CIB_shadow_dir=$io_dir $test_cmd -x $input -S &> $summary_output
     fi
 
     CIB_shadow_dir=$io_dir $test_cmd -x $input -D $dot_output -G $output -SQ -s $* 2> $stderr_output > $score_output
     rc=$?
 
     if [ $rc != $expected_rc ]; then
-	failed "Test returned: $rc";
-	did_fail=1
-	echo "CIB_shadow_dir=$io_dir $test_cmd -x $input -D $dot_output -G $output -SQ -s $*"
+        failed "Test returned: $rc";
+        did_fail=1
+        echo "CIB_shadow_dir=$io_dir $test_cmd -x $input -D $dot_output -G $output -SQ -s $*"
     fi
 
     if [ -z "$VALGRIND_SKIP_OUTPUT" ]; then
-	if [ -s ${valgrind_output} ]; then
-	    error "Valgrind reported errors";
-	    did_fail=1
-	    cat ${valgrind_output}
-	fi
-	rm -f ${valgrind_output}
+        if [ -s ${valgrind_output} ]; then
+            error "Valgrind reported errors";
+            did_fail=1
+            cat ${valgrind_output}
+        fi
+        rm -f ${valgrind_output}
     fi
 
     if [ -s core ]; then
-	error "Core-file detected: core.${base}";
-	did_fail=1
-	rm -f $test_home/core.$base
-	mv core $test_home/core.$base
+        error "Core-file detected: core.${base}";
+        did_fail=1
+        rm -f $test_home/core.$base
+        mv core $test_home/core.$base
     fi
 
     if [ -e $stderr_expected ]; then
 
-	diff $diff_opts $stderr_expected $stderr_output >/dev/null
-	rc2=$?
-	if [ $rc2 != 0 ]; then
-	    failed "stderr changed";
-	    diff $diff_opts $stderr_expected $stderr_output 2>/dev/null >> $failed
-	    echo "" >> $failed
-	    did_fail=1
-	fi
+        diff $diff_opts $stderr_expected $stderr_output >/dev/null
+        rc2=$?
+        if [ $rc2 != 0 ]; then
+            failed "stderr changed";
+            diff $diff_opts $stderr_expected $stderr_output 2>/dev/null >> $failed
+            echo "" >> $failed
+            did_fail=1
+        fi
 
     elif [ -s $stderr_output ]; then
-	error "Output was written to stderr"
-	did_fail=1
-	cat $stderr_output
+        error "Output was written to stderr"
+        did_fail=1
+        cat $stderr_output
     fi
     rm -f $stderr_output
 
     if [ ! -s $output ]; then
-	error "No graph produced";
-	did_fail=1
-	num_failed=`expr $num_failed + $did_fail`
-	rm -f $output
-	return;
-#    else
-#	mv $output $output.sed
-#	cat $output.sed | sed 's/id=.[0-9]*.\ //g' >> $output
+        error "No graph produced";
+        did_fail=1
+        num_failed=`expr $num_failed + $did_fail`
+        rm -f $output
+        return;
     fi
 
     if [ ! -s $dot_output ]; then
-	error "No dot-file summary produced";
-	did_fail=1
-	num_failed=`expr $num_failed + $did_fail`
-	rm -f $output
-	return;
+        error "No dot-file summary produced";
+        did_fail=1
+        num_failed=`expr $num_failed + $did_fail`
+        rm -f $output
+        return;
     else
-	echo "digraph \"g\" {" > $dot_output.sort
-	LC_ALL=POSIX sort -u $dot_output | grep -v -e ^}$ -e digraph >> $dot_output.sort
-	echo "}" >> $dot_output.sort
-	mv -f $dot_output.sort $dot_output
+        echo "digraph \"g\" {" > $dot_output.sort
+        LC_ALL=POSIX sort -u $dot_output | grep -v -e ^}$ -e digraph >> $dot_output.sort
+        echo "}" >> $dot_output.sort
+        mv -f $dot_output.sort $dot_output
     fi
 
     if [ ! -s $score_output ]; then
-	error "No allocation scores produced";
-	did_fail=1
-	num_failed=`expr $num_failed + $did_fail`
-	rm $output
-	return;
+        error "No allocation scores produced";
+        did_fail=1
+        num_failed=`expr $num_failed + $did_fail`
+        rm $output
+        return;
     else
-	LC_ALL=POSIX sort $score_output > $score_output.sorted
-	mv -f $score_output.sorted $score_output
+        LC_ALL=POSIX sort $score_output > $score_output.sorted
+        mv -f $score_output.sorted $score_output
     fi
 
     if [ "$create_mode" = "true" ]; then
-	cp "$output" "$expected"
-	cp "$dot_output" "$dot_expected"
-	cp "$score_output" "$scores"
-	cp "$summary_output" "$summary"
-	info "	Created expected outputs"
+        cp "$output" "$expected"
+        cp "$dot_output" "$dot_expected"
+        cp "$score_output" "$scores"
+        cp "$summary_output" "$summary"
+        info "  Created expected outputs"
     fi
 
     diff $diff_opts $summary $summary_output >/dev/null
     rc2=$?
     if [ $rc2 != 0 ]; then
-	failed "summary changed";
-	diff $diff_opts $summary $summary_output 2>/dev/null >> $failed
-	echo "" >> $failed
-	did_fail=1
+        failed "summary changed";
+        diff $diff_opts $summary $summary_output 2>/dev/null >> $failed
+        echo "" >> $failed
+        did_fail=1
     fi
 
     diff $diff_opts $dot_expected $dot_output >/dev/null
     rc=$?
     if [ $rc != 0 ]; then
-	failed "dot-file summary changed";
-	diff $diff_opts $dot_expected $dot_output 2>/dev/null >> $failed
-	echo "" >> $failed
-	did_fail=1
+        failed "dot-file summary changed";
+        diff $diff_opts $dot_expected $dot_output 2>/dev/null >> $failed
+        echo "" >> $failed
+        did_fail=1
     else
-	rm -f $dot_output
+        rm -f $dot_output
     fi
 
     sed -i -e 's/crm_feature_set="[^"]*"//' -e 's/batch-limit="[0-9]*"//' $expected $output
     diff $diff_opts $expected $output >/dev/null
     rc2=$?
     if [ $rc2 != 0 ]; then
-	failed "xml-file changed";
-	diff $diff_opts $expected $output 2>/dev/null >> $failed
-	echo "" >> $failed
-	did_fail=1
+        failed "xml-file changed";
+        diff $diff_opts $expected $output 2>/dev/null >> $failed
+        echo "" >> $failed
+        did_fail=1
     fi
 
     diff $diff_opts $scores $score_output >/dev/null
     rc=$?
     if [ $rc != 0 ]; then
-	failed "scores-file changed";
-	diff $diff_opts $scores $score_output 2>/dev/null >> $failed
-	echo "" >> $failed
-	did_fail=1
+        failed "scores-file changed";
+        diff $diff_opts $scores $score_output 2>/dev/null >> $failed
+        echo "" >> $failed
+        did_fail=1
     fi
     rm -f $output $score_output $summary_output
     num_failed=`expr $num_failed + $did_fail`
@@ -292,18 +288,18 @@ function do_test {
 
 function test_results {
     if [ $num_failed != 0 ]; then
-	if [ -s $failed ]; then
-	    if [ "$verbose" = "1" ]; then
-		error "Results of $num_failed failed tests (out of $num_tests)...."
-		cat $failed
-	    else
-		error "Results of $num_failed failed tests (out of $num_tests) are in $failed...."
-		error "Use $0 -V to display them automatically."
-	    fi
-	else
-	    error "$num_failed (of $num_tests) tests failed (no diff results)"
-	    rm $failed
-	fi
+        if [ -s $failed ]; then
+            if [ "$verbose" = "1" ]; then
+                error "Results of $num_failed failed tests (out of $num_tests)...."
+                cat $failed
+            else
+                error "Results of $num_failed failed tests (out of $num_tests) are in $failed...."
+                error "Use $0 -V to display them automatically."
+            fi
+        else
+            error "$num_failed (of $num_tests) tests failed (no diff results)"
+            rm $failed
+        fi
     fi
     exit $num_failed
 }
@@ -337,7 +333,7 @@ do_test simple3 "Start 2     "
 do_test simple4 "Start Failed"
 do_test simple6 "Stop Start  "
 do_test simple7 "Shutdown    "
-#do_test simple8 "Stonith	"
+#do_test simple8 "Stonith     "
 #do_test simple9 "Lower version"
 #do_test simple10 "Higher version"
 do_test simple11 "Priority (ne)"
@@ -345,9 +341,9 @@ do_test simple12 "Priority (eq)"
 do_test simple8 "Stickiness"
 
 echo ""
-do_test group1 "Group		"
-do_test group2 "Group + Native	"
-do_test group3 "Group + Group	"
+do_test group1 "Group                   "
+do_test group2 "Group + Native          "
+do_test group3 "Group + Group           "
 do_test group4 "Group + Native (nothing)"
 do_test group5 "Group + Native (move)   "
 do_test group6 "Group + Group (move)    "
@@ -443,7 +439,7 @@ do_test one-or-more-unrunnable-instances "Avoid dependencies on instances that w
 echo ""
 do_test order1 "Order start 1     "
 do_test order2 "Order start 2     "
-do_test order3 "Order stop	  "
+do_test order3 "Order stop        "
 do_test order4 "Order (multiple)  "
 do_test order5 "Order (move)  "
 do_test order6 "Order (move w/ restart)  "
@@ -493,8 +489,8 @@ do_test rsc-sets-clone-1 "Resource Sets - Clone (lf#2404)"
 
 #echo ""
 #do_test agent1 "version: lt (empty)"
-#do_test agent2 "version: eq	"
-#do_test agent3 "version: gt	"
+#do_test agent2 "version: eq "
+#do_test agent3 "version: gt "
 
 echo ""
 do_test attrs1 "string: eq (and)     "
@@ -621,11 +617,11 @@ do_test a-promote-then-b-migrate "A promote then B start. migrate B"
 do_test a-demote-then-b-migrate "A demote then B stop. migrate B"
 
 if [ $DO_VERSIONED_TESTS -eq 1 ]; then
-	do_test migrate-versioned "Disable migration for versioned resources"
+    do_test migrate-versioned "Disable migration for versioned resources"
 fi
 
 #echo ""
-#do_test complex1 "Complex	"
+#do_test complex1 "Complex "
 
 do_test bug-lf-2422 "Dependency on partially active group - stop ocfs:*"
 
@@ -920,29 +916,29 @@ do_test not-installed-agent "The resource agent is missing"
 do_test not-installed-tools "Something the resource agent needs is missing"
 
 echo ""
-do_test stopped-monitor-00	"Stopped Monitor - initial start"
-do_test stopped-monitor-01	"Stopped Monitor - failed started"
-do_test stopped-monitor-02	"Stopped Monitor - started multi-up"
-do_test stopped-monitor-03	"Stopped Monitor - stop started"
-do_test stopped-monitor-04	"Stopped Monitor - failed stop"
-do_test stopped-monitor-05	"Stopped Monitor - start unmanaged"
-do_test stopped-monitor-06	"Stopped Monitor - unmanaged multi-up"
-do_test stopped-monitor-07	"Stopped Monitor - start unmanaged multi-up"
-do_test stopped-monitor-08	"Stopped Monitor - migrate"
-do_test stopped-monitor-09	"Stopped Monitor - unmanage started"
-do_test stopped-monitor-10	"Stopped Monitor - unmanaged started multi-up"
-do_test stopped-monitor-11	"Stopped Monitor - stop unmanaged started"
-do_test stopped-monitor-12	"Stopped Monitor - unmanaged started multi-up (targer-role="Stopped")"
-do_test stopped-monitor-20	"Stopped Monitor - initial stop"
-do_test stopped-monitor-21	"Stopped Monitor - stopped single-up"
-do_test stopped-monitor-22	"Stopped Monitor - stopped multi-up"
-do_test stopped-monitor-23	"Stopped Monitor - start stopped"
-do_test stopped-monitor-24	"Stopped Monitor - unmanage stopped"
-do_test stopped-monitor-25	"Stopped Monitor - unmanaged stopped multi-up"
-do_test stopped-monitor-26	"Stopped Monitor - start unmanaged stopped"
-do_test stopped-monitor-27	"Stopped Monitor - unmanaged stopped multi-up (target-role="Started")"
-do_test stopped-monitor-30	"Stopped Monitor - new node started"
-do_test stopped-monitor-31	"Stopped Monitor - new node stopped"
+do_test stopped-monitor-00 "Stopped Monitor - initial start"
+do_test stopped-monitor-01 "Stopped Monitor - failed started"
+do_test stopped-monitor-02 "Stopped Monitor - started multi-up"
+do_test stopped-monitor-03 "Stopped Monitor - stop started"
+do_test stopped-monitor-04 "Stopped Monitor - failed stop"
+do_test stopped-monitor-05 "Stopped Monitor - start unmanaged"
+do_test stopped-monitor-06 "Stopped Monitor - unmanaged multi-up"
+do_test stopped-monitor-07 "Stopped Monitor - start unmanaged multi-up"
+do_test stopped-monitor-08 "Stopped Monitor - migrate"
+do_test stopped-monitor-09 "Stopped Monitor - unmanage started"
+do_test stopped-monitor-10 "Stopped Monitor - unmanaged started multi-up"
+do_test stopped-monitor-11 "Stopped Monitor - stop unmanaged started"
+do_test stopped-monitor-12 "Stopped Monitor - unmanaged started multi-up (targer-role="Stopped")"
+do_test stopped-monitor-20 "Stopped Monitor - initial stop"
+do_test stopped-monitor-21 "Stopped Monitor - stopped single-up"
+do_test stopped-monitor-22 "Stopped Monitor - stopped multi-up"
+do_test stopped-monitor-23 "Stopped Monitor - start stopped"
+do_test stopped-monitor-24 "Stopped Monitor - unmanage stopped"
+do_test stopped-monitor-25 "Stopped Monitor - unmanaged stopped multi-up"
+do_test stopped-monitor-26 "Stopped Monitor - start unmanaged stopped"
+do_test stopped-monitor-27 "Stopped Monitor - unmanaged stopped multi-up (target-role="Started")"
+do_test stopped-monitor-30 "Stopped Monitor - new node started"
+do_test stopped-monitor-31 "Stopped Monitor - new node stopped"
 
 echo""
 do_test ticket-primitive-1 "Ticket - Primitive (loss-policy=stop, initial)"
@@ -1168,7 +1164,7 @@ do_test remote-recover-fail     "Make sure start failure causes fencing if rsc a
 do_test remote-start-fail       "Make sure a start failure does not result in fencing if no active resources are on remote."
 do_test remote-unclean2         "Make monitor failure always results in fencing, even if no rsc are active on remote."
 do_test remote-fence-before-reconnect "Fence before clearing recurring monitor failure"
-do_test remote-recovery		"Recover remote connections before attempting demotion"
+do_test remote-recovery "Recover remote connections before attempting demotion"
 do_test remote-recover-connection "Optimistically recovery of only the connection"
 do_test remote-recover-all        "Fencing when the connection has no home"
 do_test remote-recover-no-resources   "Fencing when the connection has no home and no active resources"
@@ -1181,16 +1177,16 @@ do_test resource-discovery      "Exercises resource-discovery location constrain
 do_test rsc-discovery-per-node  "Disable resource discovery per node"
 
 if [ $DO_VERSIONED_TESTS -eq 1 ]; then
-	echo ""
-	do_test versioned-resources     "Start resources with #ra-version rules"
-	do_test restart-versioned       "Restart resources on #ra-version change"
-	do_test reload-versioned        "Reload resources on #ra-version change"
+    echo ""
+    do_test versioned-resources     "Start resources with #ra-version rules"
+    do_test restart-versioned       "Restart resources on #ra-version change"
+    do_test reload-versioned        "Reload resources on #ra-version change"
 
-	echo ""
-	do_test versioned-operations-1  "Use #ra-version to configure operations of native resources"
-	do_test versioned-operations-2  "Use #ra-version to configure operations of stonith resources"
-	do_test versioned-operations-3  "Use #ra-version to configure operations of master/slave resources"
-	do_test versioned-operations-4  "Use #ra-version to configure operations of groups of the resources"
+    echo ""
+    do_test versioned-operations-1  "Use #ra-version to configure operations of native resources"
+    do_test versioned-operations-2  "Use #ra-version to configure operations of stonith resources"
+    do_test versioned-operations-3  "Use #ra-version to configure operations of master/slave resources"
+    do_test versioned-operations-4  "Use #ra-version to configure operations of groups of the resources"
 fi
 
 echo ""
