Test: cts-pengine: clean up code
Add help text, validate command-line arguments better, remove dead code, and
use good shell programming practices.

diff --git a/cts/cts-pengine.in b/cts/cts-pengine.in
--- a/cts/cts-pengine.in
+++ b/cts/cts-pengine.in
@@ -17,13 +17,32 @@
  # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
  #
 
+USAGE_TEXT="Usage: cts-pengine [<options>]
+Options:
+ --help                 Display this text, then exit
+ -V, --verbose          Display any differences from expected output
+ --run TEST             Run only single specified test
+ -b, --binary PATH      Specify path to crm_simulate
+ -i, --io-dir PATH      Specify path to regression test data directory
+ -v, --valgrind         Run all commands under valgrind
+ --valgrind-dhat        Run all commands under valgrind with heap analyzer
+ --valgrind-skip-output If running under valgrind, don't display output"
+
 test_home=$(dirname $(readlink -e $0))
 verbose=0
 num_failed=0
 num_tests=0
-force_local=0
 VALGRIND_CMD=""
 diff_opts="--ignore-all-space --ignore-blank-lines -u -N"
+
+# These constants must track crm_exit_t values
+CRM_EX_OK=0
+CRM_EX_ERROR=1
+CRM_EX_NOT_INSTALLED=5
+CRM_EX_USAGE=64
+CRM_EX_NOINPUT=66
+
+EXITCODE=$CRM_EX_OK
 
 function info() {
     printf "$*\n"
@@ -47,32 +66,51 @@ io_dir="$test_home/pengine"
 test_binary=@abs_top_builddir@/tools/crm_simulate
 PCMK_schema_directory=@abs_top_builddir@/xml
 
-
 failed=$test_home/.regression.failed.diff
 single_test=
 
-while true ; do
+while [ $# -gt 0 ] ; do
     case "$1" in
-        -V|--verbose) verbose=1; shift;;
+        -V|--verbose)
+            verbose=1
+            shift
+            ;;
         -v|--valgrind)
             export G_SLICE=always-malloc
             VALGRIND_CMD="valgrind -q --gen-suppressions=all --log-file=%q{valgrind_output} --show-reachable=no --leak-check=full --trace-children=no --time-stamp=yes --num-callers=20 --suppressions=@datadir@/@PACKAGE@/tests/valgrind-pcmk.suppressions"
             test_binary=
-            shift;;
+            shift
+            ;;
         --valgrind-dhat)
             VALGRIND_CMD="valgrind --log-file=%q{valgrind_output} --show-top-n=100 --num-callers=4 --time-stamp=yes --trace-children=no --tool=exp-dhat"
             test_binary=
-            shift;;
+            shift
+            ;;
         --valgrind-skip-output)
             VALGRIND_SKIP_OUTPUT=1
-            shift;;
-        --run) single_test="$2"; shift; shift; break;;
-        -b|--binary) test_binary=$2; PCMK_schema_directory=""; shift; shift;;
-        -i|--io-dir) io_dir=$2; shift; shift;;
-        -?|--help) echo "$0 [--binary name] [--force-local]"; shift; exit 0;;
-        --) shift ; break ;;
-        "") break;;
-        *) echo "unknown option: $1"; exit 1;;
+            shift
+            ;;
+        --run)
+            single_test="$2"
+            shift 2
+            ;;
+        -b|--binary)
+            test_binary=$2
+            PCMK_schema_directory=""
+            shift 2
+            ;;
+        -i|--io-dir)
+            io_dir=$2
+            shift 2
+            ;;
+        --help)
+            echo "$USAGE_TEXT"
+            exit $CRM_EX_OK
+            ;;
+        *)
+            error "unknown option: $1"
+            exit $CRM_EX_USAGE
+            ;;
     esac
 done
 
@@ -86,9 +124,9 @@ fi
 
 export PCMK_schema_directory
 
-if [ "x$test_binary" = "x" ]; then
-    info "crm_simulate not installed. Aborting."
-    exit 1
+if [ ! -x "$test_binary" ]; then
+    error "$test_binary not found"
+    exit $CRM_EX_NOT_INSTALLED
 fi
 
 info "Test binary is:\t$test_binary"
@@ -106,11 +144,10 @@ if [ `whoami` != root ]; then
     declare -x CIB_shadow_dir=/tmp
 fi
 
-function do_test {
-
+do_test() {
     did_fail=0
     expected_rc=0
-    num_tests=`expr $num_tests + 1`
+    num_tests=$(( $num_tests + 1 ))
 
     base=$1; shift
     name=$1; shift
@@ -145,16 +182,17 @@ function do_test {
     if [ ! -f $input ]; then
         error "No input";
         did_fail=1
-        num_failed=`expr $num_failed + $did_fail`
-        return;
+        num_failed=$(( $num_failed + 1 ))
+        return $CRM_EX_NOINPUT;
     fi
 
     if [ "$create_mode" != "true" -a ! -f $expected ]; then
         error "no stored output";
+        return $CRM_EX_NOINPUT;
     fi
 
 #    ../admin/crm_verify -X $input
-    if [ ! -z $single_test ]; then
+    if [ ! -z "$single_test" ]; then
         echo CIB_shadow_dir=$io_dir $test_cmd -x $input -D $dot_output -G $output -S $*
         CIB_shadow_dir=$io_dir $test_cmd -x $input -D $dot_output -G $output -S $* 2>&1 | tee $summary_output
     else
@@ -164,14 +202,14 @@ function do_test {
     CIB_shadow_dir=$io_dir $test_cmd -x $input -D $dot_output -G $output -SQ -s $* 2> $stderr_output > $score_output
     rc=$?
 
-    if [ $rc != $expected_rc ]; then
+    if [ $rc -ne $expected_rc ]; then
         failed "Test returned: $rc";
         did_fail=1
         echo "CIB_shadow_dir=$io_dir $test_cmd -x $input -D $dot_output -G $output -SQ -s $*"
     fi
 
     if [ -z "$VALGRIND_SKIP_OUTPUT" ]; then
-        if [ -s ${valgrind_output} ]; then
+        if [ -s "${valgrind_output}" ]; then
             error "Valgrind reported errors";
             did_fail=1
             cat ${valgrind_output}
@@ -186,18 +224,18 @@ function do_test {
         mv core $test_home/core.$base
     fi
 
-    if [ -e $stderr_expected ]; then
+    if [ -e "$stderr_expected" ]; then
 
         diff $diff_opts $stderr_expected $stderr_output >/dev/null
         rc2=$?
-        if [ $rc2 != 0 ]; then
+        if [ $rc2 -ne 0 ]; then
             failed "stderr changed";
             diff $diff_opts $stderr_expected $stderr_output 2>/dev/null >> $failed
             echo "" >> $failed
             did_fail=1
         fi
 
-    elif [ -s $stderr_output ]; then
+    elif [ -s "$stderr_output" ]; then
         error "Output was written to stderr"
         did_fail=1
         cat $stderr_output
@@ -207,17 +245,17 @@ function do_test {
     if [ ! -s $output ]; then
         error "No graph produced";
         did_fail=1
-        num_failed=`expr $num_failed + $did_fail`
+        num_failed=$(( $num_failed + 1 ))
         rm -f $output
-        return;
+        return $CRM_EX_ERROR;
     fi
 
     if [ ! -s $dot_output ]; then
         error "No dot-file summary produced";
         did_fail=1
-        num_failed=`expr $num_failed + $did_fail`
+        num_failed=$(( $num_failed + 1 ))
         rm -f $output
-        return;
+        return $CRM_EX_ERROR;
     else
         echo "digraph \"g\" {" > $dot_output.sort
         LC_ALL=POSIX sort -u $dot_output | grep -v -e ^}$ -e digraph >> $dot_output.sort
@@ -228,9 +266,9 @@ function do_test {
     if [ ! -s $score_output ]; then
         error "No allocation scores produced";
         did_fail=1
-        num_failed=`expr $num_failed + $did_fail`
+        num_failed=$(( $num_failed + 1 ))
         rm $output
-        return;
+        return $CRM_EX_ERROR;
     else
         LC_ALL=POSIX sort $score_output > $score_output.sorted
         mv -f $score_output.sorted $score_output
@@ -246,7 +284,7 @@ function do_test {
 
     diff $diff_opts $summary $summary_output >/dev/null
     rc2=$?
-    if [ $rc2 != 0 ]; then
+    if [ $rc2 -ne 0 ]; then
         failed "summary changed";
         diff $diff_opts $summary $summary_output 2>/dev/null >> $failed
         echo "" >> $failed
@@ -255,7 +293,7 @@ function do_test {
 
     diff $diff_opts $dot_expected $dot_output >/dev/null
     rc=$?
-    if [ $rc != 0 ]; then
+    if [ $rc -ne 0 ]; then
         failed "dot-file summary changed";
         diff $diff_opts $dot_expected $dot_output 2>/dev/null >> $failed
         echo "" >> $failed
@@ -267,7 +305,7 @@ function do_test {
     sed -i -e 's/crm_feature_set="[^"]*"//' -e 's/batch-limit="[0-9]*"//' $expected $output
     diff $diff_opts $expected $output >/dev/null
     rc2=$?
-    if [ $rc2 != 0 ]; then
+    if [ $rc2 -ne 0 ]; then
         failed "xml-file changed";
         diff $diff_opts $expected $output 2>/dev/null >> $failed
         echo "" >> $failed
@@ -276,20 +314,24 @@ function do_test {
 
     diff $diff_opts $scores $score_output >/dev/null
     rc=$?
-    if [ $rc != 0 ]; then
+    if [ $rc -ne 0 ]; then
         failed "scores-file changed";
         diff $diff_opts $scores $score_output 2>/dev/null >> $failed
         echo "" >> $failed
         did_fail=1
     fi
     rm -f $output $score_output $summary_output
-    num_failed=`expr $num_failed + $did_fail`
+    if [ $did_fail -eq 1 ]; then
+        num_failed=$(( $num_failed + 1 ))
+        return $CRM_EX_ERROR
+    fi
+    return $CRM_EX_OK
 }
 
 function test_results {
-    if [ $num_failed != 0 ]; then
-        if [ -s $failed ]; then
-            if [ "$verbose" = "1" ]; then
+    if [ $num_failed -ne 0 ]; then
+        if [ -s "$failed" ]; then
+            if [ $verbose -eq 1 ]; then
                 error "Results of $num_failed failed tests (out of $num_tests)...."
                 cat $failed
             else
@@ -300,19 +342,20 @@ function test_results {
             error "$num_failed (of $num_tests) tests failed (no diff results)"
             rm $failed
         fi
+        EXITCODE=$CRM_EX_ERROR
     fi
-    exit $num_failed
 }
 
-if [ -z $single_test ]; then
+if [ -z "$single_test" ]; then
 # zero out the error log
     > $failed
 else
     failed=.single
     > $failed
     do_test $single_test "Single shot" $*
+    TEST_RC=$?
     cat $failed
-    exit $?
+    exit $TEST_RC
 fi
 
 DO_VERSIONED_TESTS=0
@@ -1191,3 +1234,4 @@ fi
 
 echo ""
 test_results
+exit $EXITCODE
