Feature: test: Move xml/regression.sh to cts/cts-schemas
Update cts/cts-schema.in minimally to make the script runnable from
any directory, and to try to shed light on some obfuscated shell
scripting.

Move test inputs to cts/schemas.

Closes T155

Signed-off-by: Reid Wahl <nrwahl@protonmail.com>

diff --git a/cts/cts-schemas.in b/cts/cts-schemas.in
--- a/cts/cts-schemas.in
+++ b/cts/cts-schemas.in
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!@BASH_PATH@
 #
 # Copyright 2018-2024 the Pacemaker project contributors
 #
@@ -7,11 +7,31 @@
 # This source code is licensed under the GNU General Public License version 2
 # or later (GPLv2+) WITHOUT ANY WARRANTY.
 
+# Note on portable usage of sed: GNU/POSIX/*BSD sed have a limited subset of
+# compatible functionality. Do not use the -i option, alternation (\|),
+# \0, or character sequences such as \n or \s.
+
+# Exit immediately if a command fails, with some exceptions (for example, when
+# part of an if or while condition). Treat unset variables as errors during
+# expansion. See bash(1) man page for details.
 set -eu
 
-if [ ! -d "test-2" ]; then
-    echo "$0 must be run from the xml subdirectory of a source tree"
-    exit 1
+# If readlink supports -e, use it
+readlink -e / >/dev/null 2>/dev/null
+if [ $? -eq 0 ]; then
+    test_home=$(dirname "$(readlink -e "$0")")
+else
+    test_home=$(dirname "$0")
+fi
+
+suites_dir="$test_home/schemas"
+src_dir=$(dirname "$test_home")
+
+if [ -d "$src_dir/xml" ]; then
+    export PCMK_schema_directory="$src_dir/xml"
+    echo "Using local schemas from: $PCMK_schema_directory"
+else
+    export PCMK_schema_directory=@CRM_SCHEMA_DIRECTORY@
 fi
 
 DIFF="diff -u"
@@ -19,7 +39,7 @@ DIFF_PAGER="less -LRX"
 RNG_VALIDATOR="xmllint --noout --relaxng"
 XSLT_PROCESSOR="xsltproc --nonet"
 
-# Default tests
+# Available test suites
 tests="test2to3 test2to3enter test2to3leave test2to3roundtrip cts_scheduler"
 
 #
@@ -110,12 +130,12 @@ test_explanation() {
 
     while [ $# -gt 0 ]; do
         case "$1" in
-            -o=*) _tsc_template="upgrade-${1#-o=}.xsl";;
+            -o=*) _tsc_template="$PCMK_schema_directory/upgrade-${1#-o=}.xsl";;
         esac
         shift
     done
 
-    ${XSLT_PROCESSOR} upgrade-detail.xsl "${_tsc_template}"
+    $XSLT_PROCESSOR "$PCMK_schema_directory/upgrade-detail.xsl" "$_tsc_template"
 }
 
 cleanup_module_error() {
@@ -294,15 +314,15 @@ test_runner() {
         case "$1" in
             -a=*) _tr_action="${1#-a=}";;
             -o=*) _tr_template="${1#-o=}"
-                  _tr_schema_o="pacemaker-${1#-o=}.rng";;
-            -t=*) _tr_schema_t="pacemaker-${1#-t=}.rng";;
+                  _tr_schema_o="$PCMK_schema_directory/pacemaker-${1#-o=}.rng";;
+            -t=*) _tr_schema_t="$PCMK_schema_directory/pacemaker-${1#-t=}.rng";;
             -G) _tr_mode=$((_tr_mode | (1 << 0)));;
             -D) _tr_mode=$((_tr_mode | (1 << 1)));;
             -B) _tr_mode=$((_tr_mode | (1 << 2)));;
         esac
         shift
     done
-    _tr_template="upgrade-${_tr_action:-${_tr_template:?}}.xsl"
+    _tr_template="$PCMK_schema_directory/upgrade-${_tr_action:-${_tr_template:?}}.xsl"
 
     if [ ! -f "${_tr_schema_o:?}" ] || [ ! -f "${_tr_schema_t:?}" ]; then
         emit_error "Origin and/or target schema missing, rerun make"
@@ -365,7 +385,7 @@ test2to3() {
         _t23_pattern="( ${_t23_pattern%-o} )"
     fi
 
-    find test-2 -name test-2 -o -type d -prune \
+    find "$suites_dir/test-2" -name test-2 -o -type d -prune    \
             -o -name '*.xml' ${_t23_pattern} -print \
         | env LC_ALL=C sort \
         | { case " $* " in
@@ -388,7 +408,7 @@ test2to3enter() {
         _t23e_pattern="( ${_t23e_pattern%-o} )"
     fi
 
-    find test-2-enter -name test-2-enter -o -type d -prune \
+    find "$suites_dir/test-2-enter" -name test-2-enter -o -type d -prune    \
             -o -name '*.xml' ${_t23e_pattern} -print \
         | env LC_ALL=C sort \
         | { case " $* " in
@@ -411,7 +431,7 @@ test2to3leave() {
         _t23l_pattern="( ${_t23l_pattern%-o} )"
     fi
 
-    find test-2-leave -name test-2-leave -o -type d -prune \
+    find "$suites_dir/test-2-leave" -name test-2-leave -o -type d -prune    \
             -o -name '*.xml' ${_t23l_pattern} -print \
         | env LC_ALL=C sort \
         | { case " $* " in
@@ -434,7 +454,8 @@ test2to3roundtrip() {
         _t23rt_pattern="( ${_t23rt_pattern%-o} )"
     fi
 
-    find test-2-roundtrip -name test-2-roundtrip -o -type d -prune \
+    find "$suites_dir/test-2-roundtrip" \
+            -name test-2-roundtrip -o -type d -prune    \
             -o -name '*.xml' ${_t23rt_pattern} -print \
         | env LC_ALL=C sort \
         | { case " $* " in
@@ -449,6 +470,15 @@ test2to3roundtrip() {
 # -D
 # -G ... see usage
 cts_scheduler() {
+    # @TODO This test suite yields a great many errors with -G. With some effort
+    # we could fix it, but it may be better to drop it.
+    #
+    # The cts_scheduler suite doesn't run by default. Rather, the user can
+    # explicitly request to generate reference outputs from cts/scheduler/xml,
+    # and then test against those reference. Nothing actually requires that we
+    # do this. We can create regression tests specifically for these schema
+    # upgrades: in fact, that's what the other test suites are.
+
     _tcp_mode=0
     _tcp_ret=0
     _tcp_validatewith=
@@ -456,7 +486,7 @@ cts_scheduler() {
     _tcp_schema_t=
     _tcp_template=
 
-    find ../cts/scheduler/xml -name '*.xml' | env LC_ALL=C sort \
+    find "$test_home/scheduler/xml" -name '*.xml' | env LC_ALL=C sort   \
         | { case " $* " in
                 *\ -C\ *) test_cleaner -r;;
                 *\ -X\ *) emit_result "not implemented" "option -X";;
@@ -506,11 +536,11 @@ EOF
                     "need to skip ${_tcp_origin} (schema: ${_tcp_validatewith})"
                     continue;;
             esac
-            _tcp_template="upgrade-${_tcp_schema_o}.xsl"
-            _tcp_schema_t="pacemaker-$((_tcp_schema_t + 1)).0.rng"
+            _tcp_template="$PCMK_schema_directory/upgrade-${_tcp_schema_o}.xsl"
+            _tcp_schema_t="$PCMK_schema_directory/pacemaker-$((_tcp_schema_t + 1)).0.rng"
 
             if [ "${_tcp_schema_o%%.*}" = "${_tcp_validatewith}" ]; then
-                _tcp_schema_o="pacemaker-${_tcp_schema_o}.rng"
+                _tcp_schema_o="$PCMK_schema_directory/pacemaker-${_tcp_schema_o}.rng"
             else
                 _tcp_schema_o="${_tcp_schema_t}"
             fi
@@ -589,7 +619,11 @@ test_suite() {
         esac
         shift
     done
+
+    # _ts_select contains a '@'-delimited list of test suite names from CLI
     _ts_select="${_ts_select}@"
+
+    # _ts_select_full contains a '@'-delimited list of test names
     _ts_select_full="${_ts_select_full}@"
 
     for _ts_test in ${tests}; do
@@ -597,19 +631,30 @@ test_suite() {
         _ts_test_specs=
         while true; do
             case "${_ts_select}" in
-            *@${_ts_test}@*)
-            _ts_test_specs="${_ts_select%%@${_ts_test}@*}"\
+                *@${_ts_test}@*)
+                    # A known test suite _ts_test was found in the list of
+                    # requested test suites _ts_select. Strip it out of
+                    # _ts_select.
+                    #
+                    # The purpose of this seems to be to prevent the later
+                    # _ts_select_full loop from selecting specific tests from
+                    # this suite, if the user also requested the entire suite.
+
+                    _ts_test_specs="${_ts_select%%@${_ts_test}@*}"\
 "@${_ts_select#*@${_ts_test}@}"
-            if [ "$_ts_test_specs" = "@" ]; then
-                _ts_select=  # nothing left
-            else
-                _ts_select="${_ts_test_specs}"
-            fi
-            continue
-            ;;
-            @) case "${_ts_test}" in test*) break;; esac  # filter
-            ;;
+
+                    if [ "$_ts_test_specs" = "@" ]; then
+                        _ts_select=  # nothing left
+                    else
+                        _ts_select="$_ts_test_specs"
+                    fi
+                    continue
+                    ;;
+                @)
+                    case "${_ts_test}" in test*) break;; esac  # filter
+                    ;;
             esac
+
             if [ -n "$_ts_test_specs" ]; then
                 break
             fi
@@ -619,19 +664,30 @@ test_suite() {
         _ts_test_specs=
         while true; do
             case "${_ts_select_full}" in
-            *@${_ts_test}/*)
-                _ts_test_full="${_ts_test}/${_ts_select_full#*@${_ts_test}/}"
-                _ts_test_full="${_ts_test_full%%@*}"
-                _ts_select_full="${_ts_select_full%%@${_ts_test_full}@*}"\
+                *@${_ts_test}/*)
+                    # A test was requested from a known test suite. This does
+                    # not mean the requested test actually exists, but rather
+                    # that it was requested as the form "<known_suite>/...".
+
+                    # Strip extraneous data from test path
+                    _ts_test_full="${_ts_test}/${_ts_select_full#*@${_ts_test}/}"
+                    _ts_test_full="${_ts_test_full%%@*}"
+
+                    # Strip the requested test out of _ts_select_full
+                    _ts_select_full="${_ts_select_full%%@${_ts_test_full}@*}"\
 "@${_ts_select_full#*@${_ts_test_full}@}"
-                _ts_test_specs="${_ts_test_specs} ${_ts_test_full#*/}"
-            ;;
-            *)
-            break
-            ;;
+
+                    # Strip the test suite name and slash from the test spec
+                    _ts_test_specs="${_ts_test_specs} ${_ts_test_full#*/}"
+                    ;;
+                *)
+                    break
+                    ;;
             esac
         done
 
+        # Feed the test specs (if any) as stdin to the respective test suite
+        # function _ts_test()
         for _ts_test_spec in ${_ts_test_specs}; do
             printf '%s\n' "${_ts_test_spec}"
         done | "${_ts_test}" ${_ts_pass} || _ts_ret=$?
