Refactor: cibsecret: make fatal() return new exit codes, and report error when commands fail instead of rc the command returns

diff --git a/tools/cibsecret.in b/tools/cibsecret.in
--- a/tools/cibsecret.in
+++ b/tools/cibsecret.in
@@ -17,19 +17,14 @@
 # These constants must track crm_exit_t values
 CRM_EX_OK=0
 CRM_EX_ERROR=1
-CRM_EX_INVALID_PARAM=2
-CRM_EX_UNIMPLEMENT_FEATURE=3
-CRM_EX_INSUFFICIENT_PRIV=4
+CRM_EX_NOT_INSTALLED=5
 CRM_EX_USAGE=64
+CRM_EX_UNAVAILABLE=69
+CRM_EX_OSFILE=72
 CRM_EX_CONFIG=78
-CRM_EX_OLD=103
 CRM_EX_DIGEST=104
 CRM_EX_NOSUCH=105
-CRM_EX_UNSAFE=107
 CRM_EX_EXISTS=108
-CRM_EX_MULTIPLE=109
-CRM_EX_EXPIRED=110
-CRM_EX_NOT_YET_IN_EFFECT=111
 
 LRM_CIBSECRETS="@LRM_CIBSECRETS_DIR@"
 
@@ -142,8 +137,10 @@ check_usage() {
 }
 
 fatal() {
+    rc=$1
+    shift
     echo "ERROR: $*"
-    exit $CRM_EX_ERROR
+    exit $rc
 }
 
 warn() {
@@ -156,7 +153,7 @@ info() {
 
 check_env() {
     which md5sum >/dev/null 2>&1 ||
-        fatal "please install md5sum to run $PROG"
+        fatal $CRM_EX_NOT_INSTALLED "please install md5sum to run $PROG"
     if which pssh >/dev/null 2>&1; then
         rsh=pssh_fun
         rcp_to_from=pscp_fun
@@ -172,21 +169,21 @@ check_env() {
         rsh=ssh_fun
         rcp_to_from=scp_fun
     else
-        fatal "please install pssh, pdsh, or ssh to run $PROG"
+        fatal $CRM_EX_NOT_INSTALLED "please install pssh, pdsh, or ssh to run $PROG"
     fi
     ps -ef | grep '[p]acemaker-controld' >/dev/null ||
-        fatal "pacemaker not running? $PROG needs pacemaker"
+        fatal $CRM_EX_UNAVAILABLE "pacemaker not running? $PROG needs pacemaker"
 }
 
 # This must be called (and return success) before calling $rsh or $rcp_to_from
 get_live_peers() {
     # Get local node name
     GLP_LOCAL_NODE="$(crm_node -n)"
-    [ $? -eq 0 ] || fatal "couldn't get local node name"
+    [ $? -eq 0 ] || fatal $CRM_EX_UNAVAILABLE "couldn't get local node name"
 
     # Get a list of all other cluster nodes
     GLP_ALL_PEERS="$(crm_node -l)"
-    [ $? -eq 0 ] || fatal "couldn't determine cluster nodes"
+    [ $? -eq 0 ] || fatal $CRM_EX_UNAVAILABLE "couldn't determine cluster nodes"
     GLP_ALL_PEERS="$(echo "$GLP_ALL_PEERS" | awk '{print $2}' | grep -v "^${GLP_LOCAL_NODE}$")"
 
     # Make a list of those that respond to pings
@@ -283,7 +280,7 @@ is_secret() {
 }
 
 check_cib_rsc() {
-    CCR_OUT="$($NO_CRM crm_resource -r "$1" -W 2>&1)" || fatal "$CCR_OUT"
+    CCR_OUT="$($NO_CRM crm_resource -r "$1" -W 2>&1)" || fatal $CRM_EX_NOSUCH "$CCR_OUT"
 }
 
 get_cib_param() {
@@ -324,7 +321,7 @@ localfiles() {
 
         set)
             LF_SUM="$(printf %s "$LF_VALUE" | md5sum)" ||
-                fatal "md5sum failed to produce hash for resource $LF_RSC parameter $LF_PARAM"
+                fatal $CRM_EX_ERROR "md5sum failed to produce hash for resource $LF_RSC parameter $LF_PARAM"
             LF_SUM="$(echo "$LF_SUM" | awk '{print $1}')"
             mkdir -p "$(dirname "$LF_FILE")" &&
                 echo "$LF_VALUE" > "$LF_FILE" &&
@@ -348,7 +345,7 @@ cibsecret_set() {
         [ ! -z "$CIBSET_CURRENT" ] &&
         [ "$CIBSET_CURRENT" != "$MAGIC" ] &&
         [ "$CIBSET_CURRENT" != "$CS_VALUE" ] &&
-        fatal "CIB value <$CIBSET_CURRENT> different for $rsc parameter $param; please delete it first"
+        fatal $CRM_EX_CONFIG "CIB value <$CIBSET_CURRENT> different for $rsc parameter $param; please delete it first"
     localfiles set "$rsc" "$param" "$CS_VALUE" &&
         set_cib_param "$rsc" "$param" "$MAGIC"
 }
@@ -356,14 +353,14 @@ cibsecret_set() {
 cibsecret_check() {
     check_cib_rsc "$rsc"
     is_secret "$(get_cib_param "$rsc" "$param")" ||
-        fatal "resource $rsc parameter $param not set as secret, nothing to check"
+        fatal $CRM_EX_CONFIG "resource $rsc parameter $param not set as secret, nothing to check"
     CSC_LOCAL_SUM="$(localfiles getsum "$rsc" "$param")"
     [ "$CSC_LOCAL_SUM" ] ||
-        fatal "no MD5 hash for resource $rsc parameter $param"
+        fatal $CRM_EX_OSFILE "no MD5 hash for resource $rsc parameter $param"
     CSC_LOCAL_VALUE="$(localfiles get "$rsc" "$param")"
     CSC_CALC_SUM="$(printf "%s" "$CSC_LOCAL_VALUE" | md5sum | awk '{print $1}')"
     [ "$CSC_CALC_SUM" = "$CSC_LOCAL_SUM" ] ||
-        fatal "MD5 hash mismatch for resource $rsc parameter $param"
+        fatal $CRM_EX_DIGEST "MD5 hash mismatch for resource $rsc parameter $param"
 }
 
 cibsecret_get() {
@@ -377,21 +374,21 @@ cibsecret_delete() {
 }
 
 cibsecret_stash() {
-    [ "$NO_CRM" ] && fatal "no access to Pacemaker, stash not supported"
+    [ "$NO_CRM" ] && fatal $CRM_EX_USAGE "no access to Pacemaker, stash not supported"
     check_cib_rsc "$rsc"
     CIBSTASH_CURRENT="$(get_cib_param "$rsc" "$param")"
     [ "$CIBSTASH_CURRENT" = "" ] &&
-        fatal "nothing to stash for resource $rsc parameter $param"
+        fatal $CRM_EX_NOSUCH "nothing to stash for resource $rsc parameter $param"
     is_secret "$CIBSTASH_CURRENT" &&
-        fatal "resource $rsc parameter $param already set as secret, nothing to stash"
+        fatal $CRM_EX_EXISTS "resource $rsc parameter $param already set as secret, nothing to stash"
     cibsecret_set "$CIBSTASH_CURRENT"
 }
 
 cibsecret_unstash() {
-    [ "$NO_CRM" ] && fatal "no access to Pacemaker, unstash not supported"
+    [ "$NO_CRM" ] && fatal $CRM_EX_USAGE "no access to Pacemaker, unstash not supported"
     UNSTASH_LOCAL_VALUE="$(localfiles get "$rsc" "$param")"
     [ "$UNSTASH_LOCAL_VALUE" = "" ] &&
-        fatal "nothing to unstash for resource $rsc parameter $param"
+        fatal $CRM_EX_NOSUCH "nothing to unstash for resource $rsc parameter $param"
     check_cib_rsc "$rsc"
     is_secret "$(get_cib_param "$rsc" "$param")" ||
         warn "resource $rsc parameter $param not set as secret, but we have local value so proceeding anyway"
@@ -422,5 +419,10 @@ umask 0077
 . "@OCF_ROOT_DIR@/lib/heartbeat/ocf-shellfuncs"
 
 "cibsecret_$cmd" "$value"
+rc=$?
+
+if [ $rc -ne 0 ]; then
+    fatal $CRM_EX_ERROR "$cmd(): failed with rc: $rc"
+fi
 
 # vim: set expandtab tabstop=8 softtabstop=4 shiftwidth=4 textwidth=80:
