Refactor: use plain 'echo' instead of 'echo ""'
Reference:
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/echo.html

diff --git a/tools/crm_failcount b/tools/crm_failcount
--- a/tools/crm_failcount
+++ b/tools/crm_failcount
@@ -7,30 +7,30 @@ target=`crm_node -n`
 TEMP=`getopt -o DGQVN:U:v:i:l:r: --long help,version,resource-id:,node:,uname:,attr-value:,delete-attr,get-value,attr-id:,lifetime:,quiet \
      -n 'crm_failcount' -- "$@"`
 
-if [ $? != 0 ] ; then echo "crm_failcount - A convenience wrapper for crm_attribute"; echo ""; crm_attribute -?; exit 1 ; fi
+if [ $? != 0 ] ; then echo "crm_failcount - A convenience wrapper for crm_attribute"; echo; crm_attribute -?; exit 1 ; fi
 
 # Note the quotes around `$TEMP': they are essential!
 eval set -- "$TEMP"
 
 function show_help() {
 	    echo "crm_failcount - A convenience wrapper for crm_attribute"
-	    echo ""
+	    echo
 	    echo "Set, update or remove the failcount for the specified resource on the named node"
-	    echo ""
+	    echo
 	    echo "Usage: crm_failcount -r resource_name command [options]"
 	    echo "Options:"
 	    echo " --help 		This text"
 	    echo " --version 		Version information"
 	    echo " -V, --verbose 		Increase debug output"
 	    echo " -q, --quiet 		Print only the value on stdout"
-	    echo ""
+	    echo
 	    echo " -r, --resource-id=value	The resource to update."
-	    echo ""
+	    echo
 	    echo "Commands:"
 	    echo " -G, --query 		Query the current value of the attribute/option"
 	    echo " -v, --update=value	Update the value of the attribute/option"
 	    echo " -D, --delete 		Delete the attribute/option"
-	    echo ""
+	    echo
 	    echo "Additional Options:"
 	    echo " -N, --node=value	Set an attribute for the named node (instead of the current one)."
 	    echo " -l, --lifetime=value	Until when should the setting take affect."
