Fix: tools: check for tar in crm_report
crm_report requires tar, so check for its existence up front.

diff --git a/tools/report.common.in b/tools/report.common.in
--- a/tools/report.common.in
+++ b/tools/report.common.in
@@ -128,6 +128,13 @@ fatal() {
     exit 1
 }
 
+require_tar() {
+    which tar >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        fatal "Required program 'tar' not found, please install and re-run"
+    fi
+}
+
 is_running() {
     ps -ef | egrep -qs $(echo "$1" | sed -e 's/^\(.\)/[\1]/')
 }
@@ -522,6 +529,9 @@ shrink() {
 
     cd $dir  >/dev/null 2>&1
     tar $tar_options $target $base >/dev/null 2>&1
+    if [ $? -ne 0 ]; then
+        fatal "Could not archive $base, please investigate and collect manually"
+    fi
     cd $olddir  >/dev/null 2>&1
 
     echo $target
