Low: RA: ping - Indicate if we couldn't contact attrd
Mercurial revision: 08f153a6b7301df5b8c4036a9d7692753f0b8ffc

diff --git a/extra/resources/ping b/extra/resources/ping
--- a/extra/resources/ping
+++ b/extra/resources/ping
@@ -245,6 +245,11 @@ ping_update() {
     done
     score=`expr $active \* $OCF_RESKEY_multiplier`
     attrd_updater -n $OCF_RESKEY_name -v $score -d $OCF_RESKEY_dampen $attrd_options
+    rc=$?
+    case $rc in 
+	0) ocf_debug "Updated attrd";;
+	*) ocf_log err "Could not update attrd ($rc): attrd_updater -n $OCF_RESKEY_name -v $score -d $OCF_RESKEY_dampen $attrd_options";;
+    esac
 }
 
 : ${OCF_RESKEY_name:="pingd"}
